# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_ReigistLigeiro.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RegistLigeiro(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(430, 337)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 20, 221, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 151, 16))
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setStyleSheet("")
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 100, 55, 16))
        self.label_3.setObjectName("label_3")
        self.btnexit = QtWidgets.QPushButton(Dialog)
        self.btnexit.setGeometry(QtCore.QRect(310, 280, 93, 28))
        self.btnexit.setObjectName("btnexit")
        self.btnadd = QtWidgets.QPushButton(Dialog)
        self.btnadd.setGeometry(QtCore.QRect(180, 280, 93, 28))
        self.btnadd.setObjectName("btnadd")
        self.inputmatricula = QtWidgets.QLineEdit(Dialog)
        self.inputmatricula.setGeometry(QtCore.QRect(20, 70, 113, 22))
        self.inputmatricula.setObjectName("inputmatricula")
        self.inputcor = QtWidgets.QLineEdit(Dialog)
        self.inputcor.setGeometry(QtCore.QRect(20, 120, 113, 22))
        self.inputcor.setObjectName("inputcor")
        self.inputvelocidade = QtWidgets.QLineEdit(Dialog)
        self.inputvelocidade.setGeometry(QtCore.QRect(20, 170, 113, 22))
        self.inputvelocidade.setObjectName("inputvelocidade")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(20, 150, 101, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(40, 40, 131, 41))
        self.label_5.setStyleSheet("image: url(:/regist/icons/license-plate.png);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(30, 100, 55, 16))
        self.label_6.setStyleSheet("image: url(:/regist/icons/color-palette.png);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(90, 150, 71, 21))
        self.label_7.setStyleSheet("image: url(:/regist/icons/speedometer.png);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Registration Ligeiro</span></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt;\">Matricula</span></p></body></html>"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt;\">Cor</span></p></body></html>"))
        self.btnexit.setText(_translate("Dialog", "Cancel"))
        self.btnadd.setText(_translate("Dialog", "Regist"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt;\">Velocidade Max</span></p></body></html>"))
import template.Regist


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_RegistLigeiro()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
